### ISSUE TITLE
Voltage conversion not correct

### ISSUE THREAD

**Issue by TomBric** [chandrawi/ADS1x15-ADC#2]
Hi Chandra,
using your library I figured out the following issue:
- voltage conversion e.g. as in the example ADS_read.py is not correct
- Problem is in function getMaxVoltage(self) :

def getMaxVoltage(self) :
        if self._config & 0x0E00 == 0x0000 : return 6.144
        elif self._config & 0x0E00 == 0x0100 : return 4.096
        elif self._config & 0x0E00 == 0x0200 : return 2.048
        elif self._config & 0x0E00 == 0x0400 : return 1.024
        elif self._config & 0x0E00 == 0x0800 : return 0.512
        else : return 0.256

- when setting the gain, the registers are different:
  def setGain(self, gain: int) :
        # Filter gain argument
        if gain == self.PGA_4_096V : gainRegister = 0x0200
        elif gain == self.PGA_2_048V : gainRegister = 0x0400
        elif gain == self.PGA_1_024V : gainRegister = 0x0600
        elif gain == self.PGA_0_512V : gainRegister = 0x0800
        elif gain == self.PGA_0_256V : gainRegister = 0x0A00

So the voltage returned is only half of the real value.

Can you check?
Thomas

**Comment by chandrawi** [comment]
Hi Thomas,

I checked again ADS111x datasheet and found out the the max voltage config in `getMaxVoltage()` method is incorrect like you said. I just modify the library to fix the issue. You can install library from test.pypi.org using this command.

```sh
pip install -i https://test.pypi.org/simple/ ADS1x15-ADC
```

Please check and tell me if the issue is fixed!

After that I will upload new library version to actual pypi repository.

**Comment by TomBric** [comment]
Hi Chandra,

yes, values are correct now!
Thanks for your work and update.

Thomas
